/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmartProjectRouteImport } from './routes/smart-project'
import { Route as SmartFlowRouteImport } from './routes/smart-flow'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as DemoReelRouteImport } from './routes/demo-reel'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SmartProjectRoute = SmartProjectRouteImport.update({
  id: '/smart-project',
  path: '/smart-project',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartFlowRoute = SmartFlowRouteImport.update({
  id: '/smart-flow',
  path: '/smart-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoReelRoute = DemoReelRouteImport.update({
  id: '/demo-reel',
  path: '/demo-reel',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo-reel': typeof DemoReelRoute
  '/experience': typeof ExperienceRoute
  '/smart-flow': typeof SmartFlowRoute
  '/smart-project': typeof SmartProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo-reel': typeof DemoReelRoute
  '/experience': typeof ExperienceRoute
  '/smart-flow': typeof SmartFlowRoute
  '/smart-project': typeof SmartProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo-reel': typeof DemoReelRoute
  '/experience': typeof ExperienceRoute
  '/smart-flow': typeof SmartFlowRoute
  '/smart-project': typeof SmartProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/demo-reel'
    | '/experience'
    | '/smart-flow'
    | '/smart-project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/demo-reel'
    | '/experience'
    | '/smart-flow'
    | '/smart-project'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/demo-reel'
    | '/experience'
    | '/smart-flow'
    | '/smart-project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DemoReelRoute: typeof DemoReelRoute
  ExperienceRoute: typeof ExperienceRoute
  SmartFlowRoute: typeof SmartFlowRoute
  SmartProjectRoute: typeof SmartProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smart-project': {
      id: '/smart-project'
      path: '/smart-project'
      fullPath: '/smart-project'
      preLoaderRoute: typeof SmartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-flow': {
      id: '/smart-flow'
      path: '/smart-flow'
      fullPath: '/smart-flow'
      preLoaderRoute: typeof SmartFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-reel': {
      id: '/demo-reel'
      path: '/demo-reel'
      fullPath: '/demo-reel'
      preLoaderRoute: typeof DemoReelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DemoReelRoute: DemoReelRoute,
  ExperienceRoute: ExperienceRoute,
  SmartFlowRoute: SmartFlowRoute,
  SmartProjectRoute: SmartProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
